from __future__ import annotations

# Declarative endpoint/tool tables — pure data, no logic.

READ_ENDPOINTS = {
    "containers": "/rest/container",
    "queue_simple": "/rest/queue/simple",
    "queue_tree": "/rest/queue/tree",
    "queue_type": "/rest/queue/type",
    "ppp_secrets": "/rest/ppp/secret",
    "ppp_active": "/rest/ppp/active",
    "ppp_profiles": "/rest/ppp/profile",
    "dhcp_leases": "/rest/ip/dhcp-server/lease",
    "dhcp_servers": "/rest/ip/dhcp-server",
    "dhcp_networks": "/rest/ip/dhcp-server/network",
    "ip_pools": "/rest/ip/pool",
    "vrf": "/rest/ip/vrf",
    "files": "/rest/file",
    "ipsec_policies": "/rest/ip/ipsec/policy",
    "ipsec_peers": "/rest/ip/ipsec/peer",
    "ipsec_identities": "/rest/ip/ipsec/identity",
    "hotspot_servers": "/rest/ip/hotspot",
    "hotspot_users": "/rest/ip/hotspot/user",
    "hotspot_active": "/rest/ip/hotspot/active",
    "hotspot_profiles": "/rest/ip/hotspot/profile",
    "hotspot_user_profiles": "/rest/ip/hotspot/user/profile",
    "firewall_connections": "/rest/ip/firewall/connection",
    "filter_rules": "/rest/ip/firewall/filter",
    "raw_rules": "/rest/ip/firewall/raw",
    "nat_rules": "/rest/ip/firewall/nat",
    "mangle_rules": "/rest/ip/firewall/mangle",
    "routes": "/rest/ip/route",
    "routing_rules": "/rest/routing/rule",
    "routing_tables": "/rest/routing/table",
    "interfaces": "/rest/interface",
    "interface_lists": "/rest/interface/list",
    "bridges": "/rest/interface/bridge",
    "bridge_ports": "/rest/interface/bridge/port",
    "vlan_interfaces": "/rest/interface/vlan",
    "veth_interfaces": "/rest/interface/veth",
    "wifi_interfaces": "/rest/interface/wifi",
    "wifi_registrations": "/rest/interface/wifi/registration-table",
    "ip_addresses": "/rest/ip/address",
    "arp": "/rest/ip/arp",
    "neighbors": "/rest/ip/neighbor",
    "dns": "/rest/ip/dns",
    "dns_cache": "/rest/ip/dns/cache",
    "dns_static": "/rest/ip/dns/static",
    "ip_services": "/rest/ip/service",
    "address_lists": "/rest/ip/firewall/address-list",
    "scripts": "/rest/system/script",
    "schedulers": "/rest/system/scheduler",
    "system_clock": "/rest/system/clock",
    "system_identity": "/rest/system/identity",
    "system_logging": "/rest/system/logging",
    "system_health": "/rest/system/health",
    "system_ntp_client": "/rest/system/ntp/client",
    "system_package": "/rest/system/package",
    "system_routerboard": "/rest/system/routerboard",
    "system_resource": "/rest/system/resource",
    "users": "/rest/user",
    "user_groups": "/rest/user/group",
    "wireguard_interfaces": "/rest/interface/wireguard",
    "wireguard_peers": "/rest/interface/wireguard/peers",
    "netwatch": "/rest/tool/netwatch",
    "logs": "/rest/log",
    # --- extended coverage: containers & storage ---
    "container_config": "/rest/container/config",
    "container_envs": "/rest/container/envs",
    "container_mounts": "/rest/container/mounts",
    "disks": "/rest/disk",
    "partitions": "/rest/partition",
    # --- extended coverage: system ---
    "system_package_update": "/rest/system/package/update",
    "system_history": "/rest/system/history",
    "system_jobs": "/rest/system/job",
    "system_license": "/rest/system/license",
    "system_note": "/rest/system/note",
    "routerboard_settings": "/rest/system/routerboard/settings",
    "system_resource_cpu": "/rest/system/resource/cpu",
    "system_resource_irq": "/rest/system/resource/irq",
    "system_resource_usb": "/rest/system/resource/usb",
    "certificates": "/rest/certificate",
    "certificate_settings": "/rest/certificate/settings",
    "user_aaa": "/rest/user/aaa",
    "user_ssh_keys": "/rest/user/ssh-keys",
    # --- extended coverage: interfaces & VPN ---
    "ethernet_interfaces": "/rest/interface/ethernet",
    "l2tp_clients": "/rest/interface/l2tp-client",
    "l2tp_servers": "/rest/interface/l2tp-server",
    "l2tp_server_settings": "/rest/interface/l2tp-server/server",
    "ovpn_clients": "/rest/interface/ovpn-client",
    "ovpn_servers": "/rest/interface/ovpn-server",
    "ovpn_server_settings": "/rest/interface/ovpn-server/server",
    "gre_interfaces": "/rest/interface/gre",
    "eoip_interfaces": "/rest/interface/eoip",
    "ipip_interfaces": "/rest/interface/ipip",
    "ipv6_tunnels": "/rest/interface/6to4",
    "sstp_clients": "/rest/interface/sstp-client",
    "sstp_servers": "/rest/interface/sstp-server",
    "sstp_server_settings": "/rest/interface/sstp-server/server",
    "pptp_clients": "/rest/interface/pptp-client",
    "pptp_servers": "/rest/interface/pptp-server",
    "pptp_server_settings": "/rest/interface/pptp-server/server",
    "pppoe_clients": "/rest/interface/pppoe-client",
    "pppoe_servers": "/rest/interface/pppoe-server",
    "pppoe_server_settings": "/rest/interface/pppoe-server/server",
    "bonding_interfaces": "/rest/interface/bonding",
    "lte_interfaces": "/rest/interface/lte",
    "lte_apn": "/rest/interface/lte/apn",
    "bridge_vlans": "/rest/interface/bridge/vlan",
    "bridge_mdb": "/rest/interface/bridge/mdb",
    "bridge_hosts": "/rest/interface/bridge/host",
    "bridge_nat_rules": "/rest/interface/bridge/nat",
    "bridge_msti": "/rest/interface/bridge/msti",
    "wireless_interfaces": "/rest/interface/wireless",
    "wifi_configurations": "/rest/interface/wifi/configuration",
    "wifi_channels": "/rest/interface/wifi/channel",
    "wifi_security": "/rest/interface/wifi/security",
    "wifi_datapaths": "/rest/interface/wifi/datapath",
    "wifi_provisioning": "/rest/interface/wifi/provisioning",
    "wifi_capsman": "/rest/interface/wifi/capsman",
    "wifi_interworking": "/rest/interface/wifi/interworking",
    "wifi_steering": "/rest/interface/wifi/steering",
    "wifi_eap_users": "/rest/interface/wifi/eap/users",
    "dot1x": "/rest/interface/dot1x",
    "dot1x_clients": "/rest/interface/dot1x/client",
    "dot1x_servers": "/rest/interface/dot1x/server",
    "macsec_policies": "/rest/interface/macsec/policy",
    "macsec_profiles": "/rest/interface/macsec/profile",
    "macsec_sessions": "/rest/interface/macsec/session",
    "detect_internet": "/rest/interface/detect-internet",
    "ppp_profiles_bindings": "/rest/interface/ppp/binding",
    # --- extended coverage: IP services & extras ---
    "ip_cloud": "/rest/ip/cloud",
    "dhcp_clients": "/rest/ip/dhcp-client",
    "ip_settings": "/rest/ip/settings",
    "ip_accounting": "/rest/ip/accounting",
    "ip_accounting_local_accesses": "/rest/ip/accounting/local-access",
    "ip_proxy": "/rest/ip/proxy",
    "ip_proxy_connections": "/rest/ip/proxy/connections",
    "ip_proxy_cache": "/rest/ip/proxy/cache",
    "ip_socks": "/rest/ip/socks",
    "upnp": "/rest/ip/upnp",
    "upnp_interfaces": "/rest/ip/upnp/interfaces",
    "upnp_nat_rules": "/rest/ip/upnp/natrules",
    "tftp": "/rest/ip/tftp",
    "ip_ssh": "/rest/ip/ssh",
    "ip_smb": "/rest/ip/smb",
    "ip_smb_shares": "/rest/ip/smb/shares",
    "ip_smb_users": "/rest/ip/smb/users",
    "kid_control": "/rest/ip/kid-control",
    "kid_control_devices": "/rest/ip/kid-control/device",
    "ipsec_settings": "/rest/ip/ipsec/settings",
    "ipsec_profiles": "/rest/ip/ipsec/profile",
    "ipsec_proposals": "/rest/ip/ipsec/proposal",
    "ipsec_groups": "/rest/ip/ipsec/group",
    "ipsec_mode_configs": "/rest/ip/ipsec/mode-config",
    "ipsec_active_peers": "/rest/ip/ipsec/active-peers",
    "ipsec_installed_sa": "/rest/ip/ipsec/installed-sa",
    "ipsec_statistics": "/rest/ip/ipsec/statistics",
    "ipsec_keys": "/rest/ip/ipsec/key",
    "hotspot_cookies": "/rest/ip/hotspot/cookie",
    "hotspot_hosts": "/rest/ip/hotspot/host",
    "hotspot_ip_bindings": "/rest/ip/hotspot/ip-binding",
    "hotspot_service_ports": "/rest/ip/hotspot/service-port",
    "hotspot_walled_garden": "/rest/ip/hotspot/walled-garden",
    "traffic_flow": "/rest/ip/traffic-flow",
    "traffic_flow_targets": "/rest/ip/traffic-flow/target",
    "ip_proxy_access": "/rest/ip/proxy/access",
    # --- extended coverage: IPv6 tree ---
    "ipv6_addresses": "/rest/ipv6/address",
    "ipv6_routes": "/rest/ipv6/route",
    "ipv6_pools": "/rest/ipv6/pool",
    "ipv6_neighbors": "/rest/ipv6/neighbor",
    "ipv6_settings": "/rest/ipv6/settings",
    "ipv6_nd": "/rest/ipv6/nd",
    "ipv6_dhcp_client": "/rest/ipv6/dhcp-client",
    "ipv6_dhcp_server": "/rest/ipv6/dhcp-server",
    "ipv6_dhcp_server_leases": "/rest/ipv6/dhcp-server/lease",
    "ipv6_dhcp_relay": "/rest/ipv6/dhcp-relay",
    "ipv6_filter_rules": "/rest/ipv6/firewall/filter",
    "ipv6_nat_rules": "/rest/ipv6/firewall/nat",
    "ipv6_mangle_rules": "/rest/ipv6/firewall/mangle",
    "ipv6_raw_rules": "/rest/ipv6/firewall/raw",
    "ipv6_address_lists": "/rest/ipv6/firewall/address-list",
    "ipv6_firewall_connections": "/rest/ipv6/firewall/connection",
    # --- extended coverage: tools ---
    "tool_email": "/rest/tool/e-mail",
    "tool_sms": "/rest/tool/sms",
    "tool_graph": "/rest/tool/graph",
    "tool_mac_server": "/rest/tool/mac-server",
    "tool_winbox_server": "/rest/tool/mac-server/winbox-server",
    "tool_romon": "/rest/tool/romon",
    "tool_traffic_generator": "/rest/tool/traffic-generator",
    "tool_bandwidth_server": "/rest/tool/bandwidth-server",
    "tool_profile": "/rest/tool/profile",
    "tool_flood_ping": "/rest/tool/flood-ping",
    "snmp": "/rest/snmp",
    "snmp_communities": "/rest/snmp/community",
    # --- extended coverage: routing protocols & mpls ---
    "routing_ospf_instances": "/rest/routing/ospf/instance",
    "routing_ospf_areas": "/rest/routing/ospf/area",
    "routing_ospf_ranges": "/rest/routing/ospf/area/range",
    "routing_ospf_interface_templates": "/rest/routing/ospf/interface-template",
    "routing_ospf_neighbors": "/rest/routing/ospf/neighbor",
    "routing_ospf_status": "/rest/routing/ospf/status",
    "routing_ospf_lsa": "/rest/routing/ospf/lsa",
    "routing_bgp_connections": "/rest/routing/bgp/connection",
    "routing_bgp_templates": "/rest/routing/bgp/template",
    "routing_bgp_sessions": "/rest/routing/bgp/session",
    "routing_bfd_configurations": "/rest/routing/bfd/configuration",
    "routing_pim_instances": "/rest/routing/pim/instance",
    "routing_pim_interface_templates": "/rest/routing/pim/interface-template",
    "mpls_interfaces": "/rest/mpls/interface",
    "mpls_ldp": "/rest/mpls/ldp",
    "mpls_ldp_interfaces": "/rest/mpls/ldp/interface",
    "mpls_ldp_neighbors": "/rest/mpls/ldp/neighbor",
    "mpls_ldp_accept_filters": "/rest/mpls/ldp/accept-filter",
    "mpls_ldp_advertise_filters": "/rest/mpls/ldp/advertise-filter",
    "mpls_local_bindings": "/rest/mpls/local-bindings",
    "mpls_remote_bindings": "/rest/mpls/remote-bindings",
    "mpls_forwarding_table": "/rest/mpls/forwarding-table",
    "mpls_traffic_eng": "/rest/mpls/traffic-eng",
    # --- extended coverage: capsman / user-manager / misc ---
    "capsman_interfaces": "/rest/caps-man/interface",
    "capsman_registrations": "/rest/caps-man/registration-table",
    "capsman_datapaths": "/rest/caps-man/datapath",
    "capsman_channels": "/rest/caps-man/channel",
    "capsman_configurations": "/rest/caps-man/configuration",
    "capsman_provisioning": "/rest/caps-man/provisioning",
    "capsman_managers": "/rest/caps-man/manager",
    "capsman_access_lists": "/rest/caps-man/access-list",
    "capsman_remote_caps": "/rest/caps-man/remote-cap",
    "user_manager_users": "/rest/user-manager/user",
    "user_manager_profiles": "/rest/user-manager/profile",
    "user_manager_profile_limitations": "/rest/user-manager/profile/limitation",
    "user_manager_customers": "/rest/user-manager/customer",
    "user_manager_routers": "/rest/user-manager/router",
    "zerotier": "/rest/zerotier",
    "zerotier_controllers": "/rest/zerotier/controller",
    "zerotier_peers": "/rest/zerotier/peers",
    "zerotier_moons": "/rest/zerotier/moons",
    "zerotier_planets": "/rest/zerotier/planets",
    "zerotier_status": "/rest/zerotier/status",
    "zerotier_ip": "/rest/zerotier/ip",
}

PATCHABLE_COLLECTIONS = {
    "/rest/container",
    "/rest/ip/dhcp-server",
    "/rest/ip/dhcp-server/lease",
    "/rest/ip/dhcp-server/network",
    "/rest/ip/firewall/filter",
    "/rest/ip/firewall/raw",
    "/rest/ip/firewall/address-list",
    "/rest/ip/firewall/mangle",
    "/rest/ip/firewall/nat",
    "/rest/ip/route",
    "/rest/ip/address",
    "/rest/ip/dns/static",
    "/rest/ip/service",
    "/rest/interface/list",
    "/rest/interface/bridge",
    "/rest/interface/bridge/port",
    "/rest/interface/vlan",
    "/rest/ip/pool",
    "/rest/interface/wireguard",
    "/rest/system/scheduler",
    "/rest/system/identity",
    "/rest/system/logging",
    "/rest/system/package",
    "/rest/system/routerboard",
    "/rest/system/script",
    # --- extended coverage: interfaces & vpn ---
    "/rest/interface/list/member",
    "/rest/interface/veth",
    "/rest/interface/wireguard/peers",
    "/rest/interface/ethernet",
    "/rest/interface/wifi",
    "/rest/interface/wifi/configuration",
    "/rest/interface/wifi/channel",
    "/rest/interface/wifi/security",
    "/rest/interface/wifi/datapath",
    "/rest/interface/wifi/provisioning",
    "/rest/interface/wifi/interworking",
    "/rest/interface/wifi/steering",
    "/rest/interface/wifi/eap/users",
    "/rest/interface/wireless",
    "/rest/interface/l2tp-client",
    "/rest/interface/l2tp-server",
    "/rest/interface/ovpn-client",
    "/rest/interface/ovpn-server",
    "/rest/interface/gre",
    "/rest/interface/eoip",
    "/rest/interface/ipip",
    "/rest/interface/6to4",
    "/rest/interface/sstp-client",
    "/rest/interface/sstp-server",
    "/rest/interface/pptp-client",
    "/rest/interface/pptp-server",
    "/rest/interface/pppoe-client",
    "/rest/interface/pppoe-server",
    "/rest/interface/bonding",
    "/rest/interface/lte",
    "/rest/interface/lte/apn",
    "/rest/interface/bridge/vlan",
    "/rest/interface/bridge/mdb",
    "/rest/interface/bridge/nat",
    "/rest/interface/bridge/msti",
    "/rest/interface/dot1x",
    "/rest/interface/dot1x/client",
    "/rest/interface/dot1x/server",
    "/rest/interface/macsec/policy",
    "/rest/interface/macsec/profile",
    "/rest/interface/detect-internet",
    # --- extended coverage: ip ---
    "/rest/ip/dhcp-client",
    "/rest/ip/dns",
    "/rest/ip/dns/cache",
    "/rest/ip/cloud",
    "/rest/ip/settings",
    "/rest/ip/upnp",
    "/rest/ip/upnp/interfaces",
    "/rest/ip/socks",
    "/rest/ip/proxy",
    "/rest/ip/proxy/access",
    "/rest/ip/smb",
    "/rest/ip/smb/shares",
    "/rest/ip/smb/users",
    "/rest/ip/kid-control",
    "/rest/ip/kid-control/device",
    "/rest/ip/ipsec/policy",
    "/rest/ip/ipsec/peer",
    "/rest/ip/ipsec/identity",
    "/rest/ip/ipsec/profile",
    "/rest/ip/ipsec/proposal",
    "/rest/ip/ipsec/group",
    "/rest/ip/ipsec/mode-config",
    "/rest/ip/ipsec/key",
    "/rest/ip/hotspot",
    "/rest/ip/hotspot/user",
    "/rest/ip/hotspot/user/profile",
    "/rest/ip/hotspot/profile",
    "/rest/ip/hotspot/ip-binding",
    "/rest/ip/hotspot/walled-garden",
    "/rest/ip/hotspot/service-port",
    "/rest/ip/traffic-flow",
    "/rest/ip/traffic-flow/target",
    "/rest/ppp/secret",
    "/rest/ppp/profile",
    "/rest/queue/simple",
    "/rest/queue/tree",
    "/rest/routing/rule",
    "/rest/routing/table",
    # --- extended coverage: ipv6 ---
    "/rest/ipv6/address",
    "/rest/ipv6/route",
    "/rest/ipv6/pool",
    "/rest/ipv6/settings",
    "/rest/ipv6/nd",
    "/rest/ipv6/dhcp-client",
    "/rest/ipv6/dhcp-server",
    "/rest/ipv6/dhcp-server/lease",
    "/rest/ipv6/dhcp-relay",
    "/rest/ipv6/firewall/filter",
    "/rest/ipv6/firewall/nat",
    "/rest/ipv6/firewall/mangle",
    "/rest/ipv6/firewall/raw",
    "/rest/ipv6/firewall/address-list",
    # --- extended coverage: system/users/certs/tools ---
    "/rest/system/ntp/client",
    "/rest/system/routerboard/settings",
    "/rest/system/note",
    "/rest/certificate",
    "/rest/certificate/settings",
    "/rest/user",
    "/rest/user/group",
    "/rest/user/aaa",
    "/rest/user/ssh-keys",
    "/rest/snmp",
    "/rest/snmp/community",
    "/rest/tool/e-mail",
    "/rest/tool/sms",
    "/rest/tool/netwatch",
    "/rest/tool/graph",
    "/rest/tool/mac-server",
    "/rest/tool/mac-server/winbox-server",
    "/rest/tool/romon",
    "/rest/ip/firewall/connection",
    # --- extended coverage: routing protocols & mpls ---
    "/rest/routing/ospf/instance",
    "/rest/routing/ospf/area",
    "/rest/routing/ospf/area/range",
    "/rest/routing/ospf/interface-template",
    "/rest/routing/bgp/connection",
    "/rest/routing/bgp/template",
    "/rest/routing/bfd/configuration",
    "/rest/routing/pim/instance",
    "/rest/routing/pim/interface-template",
    "/rest/mpls/interface",
    "/rest/mpls/ldp",
    "/rest/mpls/ldp/interface",
    "/rest/mpls/ldp/accept-filter",
    "/rest/mpls/ldp/advertise-filter",
    "/rest/mpls/traffic-eng",
    # --- extended coverage: capsman & user-manager ---
    "/rest/caps-man/interface",
    "/rest/caps-man/datapath",
    "/rest/caps-man/channel",
    "/rest/caps-man/configuration",
    "/rest/caps-man/provisioning",
    "/rest/caps-man/manager",
    "/rest/caps-man/access-list",
    "/rest/caps-man/remote-cap",
    "/rest/user-manager/user",
    "/rest/user-manager/profile",
    "/rest/user-manager/profile/limitation",
    "/rest/user-manager/customer",
    "/rest/user-manager/router",
    "/rest/zerotier",
    "/rest/zerotier/controller",
}

MUTATION_ALLOWLIST = {
    "/rest/ip/dns/cache/flush",
    "/rest/system/script/run",
    *PATCHABLE_COLLECTIONS,
}



LISTED_GET_TOOLS = frozenset(
    {
        "get_containers",
        "get_dhcp_leases",
        "get_dhcp_servers",
        "get_dns",
        "get_dns_static",
        "get_dns_cache",
        "get_address_lists",
        "get_mangle_rules",
        "get_nat_rules",
        "get_filter_rules",
        "get_firewall_connections",
        "get_routes",
        "get_routing_rules",
        "get_routing_tables",
        "get_interfaces",
        "get_interface_lists",
        "get_veth_interfaces",
        "get_wireguard_interfaces",
        "get_wireguard_peers",
        "get_ip_addresses",
        "get_schedulers",
        "get_scripts",
        "get_system_resource",
        "get_system_identity",
        "get_system_clock",
        "get_system_health",
        "get_system_logging",
        "get_logs",
        "get_files",
        "get_neighbors",
        "get_arp",
        "get_wifi_interfaces",
        "get_wifi_registrations",
        "get_ip_cloud",
        "get_system_package_update",
        "get_disks",
    }
)


READONLY_TOOLS = frozenset(
    {
        "routeros_get",
        "read_file",
        "run_ping",
        "run_traceroute",
        "run_wifi_monitor",
        "routeros_batch",
        "describe_path",
        "interface_traffic",
        "routeros_watch",
        "catalog_search",
        "safe_status",
    }
)
DESTRUCTIVE_TOOLS = frozenset(
    {
        "routeros_write",
        "patch_resource_by_id",
        "delete_file",
        "rename_file",
        "update_file",
        "create_file",
        "upload_file",
        "save_backup",
        "save_export",
        "flush_dns_cache",
        "run_script",
        "container_shell",
        "download_file",
        "run_fetch",
        "apply_safe",
        "commit_safe",
        "run_script_inline",
    }
)


